### ISSUE TITLE
Drop invalid enumerated values with a warning

### ISSUE THREAD

**Issue by Rahix** [Rahix/atdf2svd#13]
In newer versions of `svd2rust` it has become a hard error when an enumerated value does not fit into the field it is meant for.  This has lead to a lot of additional patches being necessary in `avr-device`: Rahix/avr-device#64

I suggest that `atdf2svd` should just not emit any enumerated values which are beyond the field-size and drop them with a warning.  This would mean we at least don't have to patch every single one of these cases right away.

In code this means that here

https://github.com/Rahix/atdf2svd/blob/a3385d1dd2ac393d05e76ae65997f69b4d1b7f74/src/atdf/field.rs#L29-L35

we need to filter the values by their validity for the current field.

**Comment by explicite** [comment]
Not sure if I'm correct. We should check mask `bitfield_el` with `value` from values? I

**Comment by Rahix** [comment]
Yeah, that is correct!  [`utils::parse_int()`](https://github.com/Rahix/atdf2svd/blob/a3385d1dd2ac393d05e76ae65997f69b4d1b7f74/src/util.rs#L4) can be used for extracting the value from mask.

**Comment by explicite** [comment]
Nice so I will try to use [drain_filter](https://doc.rust-lang.org/beta/std/collections/struct.BTreeMap.html#method.drain_filter).
Not sure how should I compare value with mask. Should I apply mask to value and then check `range` and `unsafe_range`?

**Comment by Rahix** [comment]
> Nice so I will try to use drain_filter.

Hmm, not sure if `drain_filter` is the way to go, especially because it's a nightly only API and in general `atdf2svd` should compile on stable ...

I would personally attempt something like

```rust
values
    .iter()                               // Gives iterator over (&K, &V)
    .filter(|_, ev| /* ev.value ... */)   // Filter any values that are outside range
    .map(|(k, v)| (k.clone(), v.clone())) // Clone the remaining ones, yield iterator over (K, V)
    .collect();                           // Collect into BTreeMap again
```

> Should I apply mask to value and then check range and unsafe_range?

Essentially you want to enforce that the enumerated values does not contain any bits outside the mask.  There are a few ways you can archieve that:

- `(ev.value & mask) == ev.value` - After masking the value, no bits should have been 'chopped off'.
- `ev.value & ~mask == 0` - Applying the negative mask, no bits should remain.

I'm not sure what is more clear ...

---

Also, please warn when any value is not okay.  I think the easiest way to do this is inside the filter:

```rust
.filter(|_, ev| if ... {
    true
} else {
    log::warn!(/* ... */);
    false
})
```
