### ISSUE TITLE
Handling of multiple declaration/meanings of the same interrupt vector

### ISSUE THREAD

**Issue by trembel** [Rahix/atdf2svd#17]
New AVR MCUs contain a list containing all interrupts, similar to the following (`attiny412.atdf`):
```
      <interrupts>
        <interrupt index="1" module-instance="CRCSCAN" name="NMI"/>
        <interrupt index="2" module-instance="BOD" name="VLM"/>
        <interrupt index="3" module-instance="PORTA" name="PORT"/>
        <interrupt index="6" module-instance="RTC" name="CNT"/>
        <interrupt index="7" module-instance="RTC" name="PIT"/>
        <interrupt index="8" module-instance="TCA0" name="LUNF"/>
        <interrupt index="8" module-instance="TCA0" name="OVF"/>
        <interrupt index="9" module-instance="TCA0" name="HUNF"/>
        <interrupt index="10" module-instance="TCA0" name="CMP0"/>
        <interrupt index="10" module-instance="TCA0" name="LCMP0"/>
        <interrupt index="11" module-instance="TCA0" name="CMP1"/>
        <interrupt index="11" module-instance="TCA0" name="LCMP1"/>
        <interrupt index="12" module-instance="TCA0" name="CMP2"/>
        <interrupt index="12" module-instance="TCA0" name="LCMP2"/>
        <interrupt index="13" module-instance="TCB0" name="INT"/>
        <interrupt index="14" module-instance="TCD0" name="OVF"/>
        <interrupt index="15" module-instance="TCD0" name="TRIG"/>
        <interrupt index="16" module-instance="AC0" name="AC"/>
        <interrupt index="17" module-instance="ADC0" name="RESRDY"/>
        <interrupt index="18" module-instance="ADC0" name="WCOMP"/>
        <interrupt index="19" module-instance="TWI0" name="TWIS"/>
        <interrupt index="20" module-instance="TWI0" name="TWIM"/>
        <interrupt index="21" module-instance="SPI0" name="INT"/>
        <interrupt index="22" module-instance="USART0" name="RXC"/>
        <interrupt index="23" module-instance="USART0" name="DRE"/>
        <interrupt index="24" module-instance="USART0" name="TXC"/>
        <interrupt index="25" module-instance="NVMCTRL" name="EE"/>
      </interrupts>
```
Some of those interrupt vectors, have multiple meanings depending on the configurations.
![attiny_isr](https://user-images.githubusercontent.com/28383252/99982511-f13e1500-2daa-11eb-833c-5ec2945fad6f.png)
An example of this is the `TCA0` peripheral, where the two modes "Normal Mode" and "Split Mode" exist - both using the same interrupt vector, both with different meanings on it:
![attiny_tca](https://user-images.githubusercontent.com/28383252/99982525-f7cc8c80-2daa-11eb-8ff3-aba4b9069e40.png)

**Comment by trembel** [comment]
Additional informations in #15

**Comment by Rahix** [comment]
I think we'll have to choose one of the two (just use the first one?) here ... Later, we can patch the name to be more descriptive/fitting in `avr-device`, using [`svdtools`](https://github.com/stm32-rs/svdtools).

**Comment by trembel** [comment]
Where is the desired place to fix this?

**Comment by Rahix** [comment]
Yes, `atdf/chip.rs` I suppose ... Ideally the code should be emitting a warning for each duplicate interrupt which it is dropping.

**Comment by trembel** [comment]
Ok. Since we collect into a `BTreeMap`, one option would be to first collect to a `BTreeMap<usize, chip::Interrupt>`, and afterwards remap to `BTreeMap<std::string::String, chip::Interrupt>`. In this case always the last entry having the same index is kept.
Another option would be to collect into a `Vec<(usize, chip::Interrupt)>`, and then filter duplicates using `.dedup_by(|(idx1, _), (idx2, _)| idx1 == idx2)`, to always keep the first entry. 

However I'm not sure which way to go, since not always the first entry is the more important, e.g.:
Here for sure the `OVF` interrupt is more often used:
```
        <interrupt index="8" module-instance="TCA0" name="LUNF"/>
        <interrupt index="8" module-instance="TCA0" name="OVF"/>
```
Here for sure the `CMP0` interrupt is more often used:
```
        <interrupt index="10" module-instance="TCA0" name="CMP0"/>
        <interrupt index="10" module-instance="TCA0" name="LCMP0"/>
```

**Comment by Rahix** [comment]
IMO this will always be a compromise and atdf2svd will unavoidable choose the "worse" name in 50% of cases.  To me, the most important thing is that we chose _something_ and that it is _deterministic_ (for a given input, we always choose the same name).  As I said, the interrupt will most likely be renamed in `avr-device` later anyway (e.g. to `TCA0_LUNF_OVF`/`TCA0_CMP0_LCMP0`), we just have to emit something here ...

My personal suggestion would be to choose the first one but I am not strongly in favor of this, so if another approach turns out much easier, that's fine by me.

What I would find important is that we emit explicit warnings for each interrupt name which is discarded.  Otherwise people won't be aware that they need to apply svd patches for the names.

**Comment by trembel** [comment]
What if we directly name it `TCA_LUNF_OVF`? That is, concatenating the "names" of the duplicated indexes?

**Comment by Rahix** [comment]
Hmm, if this is easily implemented, sure.  But I wouldn't waste too much effort here as patching the names later is probably _much_ easier and might still be needed if the generated names are non-descriptive ...

BTW, how do the C headers name those interrupts?  The C runtime surely cannot deal with multiple definitions of an interrupt handler either?

**Comment by trembel** [comment]
I'll give it a look.

This is what it looks like in the attiny412 header:
```
/* TCA0 interrupt vectors */
#define TCA0_LUNF_vect_num  8
#define TCA0_LUNF_vect      _VECTOR(8)  /*  */
#define TCA0_OVF_vect_num  8
#define TCA0_OVF_vect      _VECTOR(8)  /*  */
#define TCA0_HUNF_vect_num  9
#define TCA0_HUNF_vect      _VECTOR(9)  /*  */
#define TCA0_CMP0_vect_num  10
#define TCA0_CMP0_vect      _VECTOR(10)  /*  */
#define TCA0_LCMP0_vect_num  10
#define TCA0_LCMP0_vect      _VECTOR(10)  /*  */
#define TCA0_CMP1_vect_num  11
#define TCA0_CMP1_vect      _VECTOR(11)  /*  */
#define TCA0_LCMP1_vect_num  11
#define TCA0_LCMP1_vect      _VECTOR(11)  /*  */
#define TCA0_CMP2_vect_num  12
#define TCA0_CMP2_vect      _VECTOR(12)  /*  */
#define TCA0_LCMP2_vect_num  12
#define TCA0_LCMP2_vect      _VECTOR(12)  /*  */
```
The definition of the interrupt handler is then done with `ISR(TCA0_OVF_vect)`, where a duplicate definition would (as far as I know) give a compiler or linker error.
